
version: '3.8'

services:
  # FastAPI приложение
  api:
    build: .
    container_name: my_library_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # Монтируем код для hot reload
      - ./:/app
    working_dir: /app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - library-network

volumes:
  sqlite_data:
    driver: local

networks:
  library-network:
    driver: bridge